# Generated by Django 3.2.9 on 2021-11-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_bio',
            field=models.TextField(default=''),
        ),
    ]
