# Generated by Django 3.2.9 on 2021-11-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211123_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_role',
            field=models.CharField(choices=[('animator', 'Animator'), ('scriptwriter', 'Scriptwriter'), ('audio engineer', 'Audio Engineer'), ('graphic design', 'Graphic Design'), ('videographer', 'Videographer'), ('video editor', 'Video Editor'), ('none', 'None')], default='none', max_length=80),
        ),
    ]
