# Generated by Django 3.2.9 on 2021-11-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_commitment_level',
            field=models.CharField(choices=[('casual', 'Casual'), ('side project', 'Side Project'), ('1 priority', '#1 Priority')], default='Casual', max_length=80),
        ),
    ]
