# Generated by Django 3.2.9 on 2021-11-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_user_commitment_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_bio',
            field=models.TextField(blank=True, default='', max_length=320),
        ),
    ]
